apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"

spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
